---
# Per environment values which override defaults in hmpps-probation-frontend-component-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: probation-frontend-components-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://probation-frontend-components-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"

    ALLOCATE_A_PERSON_ON_PROBATION_URL: "https://workforce-management-preprod.hmpps.service.justice.gov.uk"
    APPROVED_PREMISES_URL: "https://approved-premises-preprod.hmpps.service.justice.gov.uk"
    CONSIDER_A_RECALL_URL: "https://consider-a-recall-preprod.hmpps.service.justice.gov.uk"
    CREATE_AND_VARY_A_LICENCE_URL: "https://create-and-vary-a-licence-preprod.hmpps.service.justice.gov.uk"
    MANAGE_PEOPLE_ON_PROBATION_URL: "https://manage-people-on-probation-preprod.hmpps.service.justice.gov.uk"
    NDELIUS_URL: "https://ndelius.pre-prod.delius.probation.hmpps.dsd.io"
    OASYS_URL: "https://pp.oasys.service.justice.gov.uk"
    PREPARE_A_CASE_URL: "https://prepare-a-case-preprod.apps.live-1.cloud-platform.service.justice.gov.uk"
    REFER_AND_MONITOR_URL: "https://hmpps-interventions-ui-preprod.apps.live-1.cloud-platform.service.justice.gov.uk"
    TRANSITIONAL_ACCOMODATION_URL: "https://transitional-accommodation-preprod.hmpps.service.justice.gov.uk"
    WORKLOAD_MEASUREMENT_TOOL_URL: "https://workload-measurement-preprod.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: NON_PROD_ALERTS_SEVERITY_LABEL
